kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ${project.artifactId}
spec:
  selector:
    name: ${project.artifactId}
  replicas: 1
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization:
    targetCPUUtilizationPercentage: 80
  template:
    metadata:
      labels:
        name: ${project.artifactId}
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: >-
                -Xmx1500m
                -Dvertx.cacheDirBase=/tmp/vertx
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: database-name
